### PR TITLE
Use Semantic release to publish release notes and to NPM

### PR DESCRIPTION
**Pull request by superflyxxi**

### CODE REVIEW

**Comment by daniloab** [comment]
can we add a previous step to ask if we want to release it? Then, only when allowing the publish will be called?

**Comment by superflyxxi** [comment]
Yeah. I'll have to look into how to do that with git flows. You want a manual approval step before it attempts to publish.

**Comment by superflyxxi** [comment]
The closest I found was this: https://docs.github.com/en/actions/managing-workflow-runs/reviewing-deployments and this https://cloudlumberjack.com/posts/github-actions-approvals/

I guess if we set up a production npm "Environment" in github, you can configure it to require approvals. In that "Environment", you can add a secret for `NPM_AUTH_TOKEN`. Finally, I can have the github action references that "Environment" to fetch its secret. And it would require approval before it happens.

How does it sound?

**Comment by daniloab** [comment]
> The closest I found was this: https://docs.github.com/en/actions/managing-workflow-runs/reviewing-deployments and this https://cloudlumberjack.com/posts/github-actions-approvals/
> 
> I guess if we set up a production npm "Environment" in github, you can configure it to require approvals. In that "Environment", you can add a secret for `NPM_AUTH_TOKEN`. Finally, I can have the github action references that "Environment" to fetch its secret. And it would require approval before it happens.
> 
> How does it sound?

I like this flow but the one problem is that I cant create an environment var to the repo. Maybe @chdanielmueller can help us on this to make the release more robust?

**Comment by superflyxxi** [comment]
Hey all, what should we do? I'm okay with letting this close.

**Pull request closed without merging**
