### PR TITLE
feat: publish to npm for master branch

### PR DESCRIPTION
**Pull request by superflyxxi**
Publish changes to npm repository. Calling it a feat since from what I've seen in the commits, there's been features introduced worthy of a minor version bump.

### CODE REVIEW

**Comment by daniloab** [comment]
I dont have sure about this workflow being automated.

**Comment by superflyxxi** [comment]
I wasn't sure why it was commented out. Do you know what issue was there?

**Comment by superflyxxi** [comment]
https://github.com/Surnet/swagger-jsdoc/pull/227 is the one that commented it out, but seems unrelated. The commit specifically only has comment "turn off automated publishing for major bump". https://github.com/Surnet/swagger-jsdoc/pull/227/commits/bb6a9ee2217f13f604760f08b80a92350169e2e7

**Comment by superflyxxi** [comment]
Is it possible to merge this? This repo has not had a release in over 1 year.

**Comment by daniloab** [comment]
Yes, actually I'm the one looking and trying to take care of this repo.

I'm preparing to list the principal issues to be fixed and prepare the next major release for the lib. 

Also, I want to publish the docs of swagger-jsdoc moving from the readme to a docusaurus page. If someone is interested in to help this feel free to contact me.

**Comment by superflyxxi** [comment]
The good news is that npm has the latest version, but github is not updated with new release version (but tag v6.2.0 is there).

npm: https://www.npmjs.com/package/swagger-jsdoc
github: https://github.com/Surnet/swagger-jsdoc/releases/tag/v6.2.0

**Pull request merged**
