### PR TITLE
CLI

### PR DESCRIPTION
**Pull request by kalinchernev**
In relation to #24 

It's re-using the main module 100%, only accepts input from user and validates the required.
Example definition file and documentation are included.

I'm open for feedback :)

### CODE REVIEW

**Comment by chdanielmueller** [comment]
Hi @drGrove,
Would you like to take a look at this?

**Comment by kalinchernev** [comment]
Hi @chdanielmueller when I click on the codacy check details I can't see any details as pointed out from the line-by-line part. When I click on any of the individual links they lead me to my master and the errors are not in the report.
Could you please help me on how to get these details to be able to fix them?
Thanks!

**Comment by chdanielmueller** [comment]
Hi @kalinchernev 
Sorry for the late answer. Has been a busy time. I hope to take a look at this on friday.
Please ignore the codacy checks as I am removing this service.
Thanks!

**Comment by drGrove** [comment]
@chdanielmueller will pull tonight and review. Sorry for the late response.

**Comment by kalinchernev** [comment]
Hi chdanielmueller, drGrove,
I was anyway offline last week, so no worries for delays, no hurry.
Thanks for your feedback when you have the opportunity!

**Comment by chdanielmueller** [comment]
Hi @drGrove,
How is your review going?

**Comment by drGrove** [comment]
Linked it globally and ran it against one of my rather large projects and it held up well.

I like the support for multiple globs, which make it nice for a folder heavy project where everything is split up and with the different types of definitions.

This kind of setup does require that the swaggerDef is not nested within a the swagger init call (which isn't the end of the world but we should make sure that people know that).

I would like to see some more test cases. None of my project have any real security definitions (yet), so i couldn't test that. But all in all this is really great :smile:. 

@kalinchernev, mind adding some more tests to make sure this is fully tested?

**Side note**: Swagger supports yaml input/output, should we as well? 

Here's a couple of tools for yaml parsing:

* [yaml2json](https://www.npmjs.com/package/yaml2json)
* [json2yaml](https://www.npmjs.com/package/json2yaml)

**Comment by kalinchernev** [comment]
Hi @drGrove and thanks for the review!

> This kind of setup does require that the swaggerDef is not nested within a the swagger init call (which isn't the end of the world but we should make sure that people know that).
Could you please elaborate a bit, I don't understand it.

> @kalinchernev, mind adding some more tests to make sure this is fully tested?
Yes, sure! I started writing some but the way the tests are setup is not easy to get into the flow. I'll spend time on this.

> Side note: Swagger supports yaml input/output, should we as well?
Do you mean that we should also forsee parging yml files? I thought the module aims for parsing jsDoc comments from .js files?

**Comment by drGrove** [comment]
>Side note: Swagger supports yaml input/output, should we as well?
>Do you mean that we should also forsee parging yml files? I thought the module aims for parsing > jsDoc comments from .js files?

You're right, ignore me there

> This kind of setup does require that the swaggerDef is not nested within a the swagger init call > > (which isn't the end of the world but we should make sure that people know that).
> Could you please elaborate a bit, I don't understand it.

I wrote a yo generator for [koa apis][gkbp], in this i nest the swaggerDef into the [index.js] [gkbp-index]. If i were to include this as the swaggerdef, it would try and run the file (since it's been required). Basically what I mean is that the swaggerDef needs to be more stand-alone (which is fine), i'll actually adjust my project for this (since it more modular that way).

[gkbp]: https://github.com/drGrove/generator-koa-bp
[gkbp-index]: https://github.com/drGrove/generator-koa-bp/blob/master/generators/app/templates/_index.js#L68

**Comment by kalinchernev** [comment]
@drGrove thanks for the examples. I have to be honest that it takes me some time to understand it, but theoretically the solution could be considered somewhere in the instantiation phase to check if an existing configuration is present or not. I'll have to dig into that further.

**Comment by kalinchernev** [comment]
@drGrove @chdanielmueller I added tests for the checks and scenarios of the application, please tell me if they are ok?

**Comment by drGrove** [comment]
@chdanielmueller I think this is ready for merge

**Comment by chdanielmueller** [comment]
@drGrove I'm also fine with this. Thank you very much for taking a look at it.

Would you like to merge it yourself, bump the version number to v1.4.0, create a new GitHub Tag and push it to npmjs?

**Comment by kalinchernev** [comment]
@drGrove @chdanielmueller thanks for the heads up!
I've just updated the version for the release :)

**Comment by kalinchernev** [comment]
Thanks @drGrove!

**Pull request merged**
