### PR TITLE
Include .yaml, and able to define responses, parameters and securityDefinitions

### PR DESCRIPTION
**Pull request by efmr**
Document responses, parameters and securityDefinitions in a similar fashion as for definitions.
Able to include directly yaml files as apis (that will be merged with the jsdoc comments).
Tests included, but increased max statements from 15 to 18 and max complexity from 6 to 8 to pass the jshint test.

### CODE REVIEW

**Comment by chdanielmueller** [comment]
Hey @efmr.
I will take a look at this and merge it if I don't find any problems.
I hope I can give you a feedback in the next week. (I'm on a tight schedule at the moment)
@drGrove: Or would you like to check this addition to the project?
Regards,
Daniel

**Comment by drGrove** [comment]
@chdanielmueller: Busy week myself but should have some time in the next couple of days. I am more than happy to look at it though

**Comment by drGrove** [comment]
:+1: 
Looks good. Actually ran it against some code i'm working on with securityDefinitions and replaces the code i was working on.

@chdanielmueller Looks good to merge

**Comment by chdanielmueller** [comment]
@efmr: Sorry for taking so long to merge this.
It is now published an available in v1.2.0 on npm.

**Comment by chdanielmueller** [comment]
@drGrove: Thanks for testing this out!

**Comment by drGrove** [comment]
@chdanielmueller: Not a problem! Let me know if you need anything else.

**Comment by efmr** [comment]
@chdanielmueller no problem.

**Pull request merged**
