### PR TITLE
chore: bump dependencies

### PR DESCRIPTION
**Pull request by jaas666**
- Bumps glob from vulnerable v7.1.6 to v11.0.0
- Bumps jest from v26.6.1 to v29.7.0

Should solve vulnerability mentioned in #277

### CODE REVIEW

**Comment by jackbridger** [comment]
Would really appreciate if this could be merged

**Review by tchim — APPROVED** [review]
lgtm

**Comment by dannyhchan** [comment]
Same, can this be merged?

**Comment by kerwenzhang** [comment]
Please help merge this, thanks.

**Comment by jaas666** [comment]
> @jaas666 Why was this closed?

I think because the versions on my PR were also outdated by the tine it was closed.

Cant really remember.

**Pull request closed without merging**
