### PR TITLE
fix(specification): apply fix for multiple anchors

### PR DESCRIPTION
**Pull request by goldsziggy**
Adjusted the when the delete of the error array happens so everything gets deleted after processing.  Also ensured deletes happen from the back of the array to fix any potential array re-ordering issues that may arrise.

Fix  Issue #252
https://github.com/Surnet/swagger-jsdoc/issues/252

### CODE REVIEW

**Comment by kalinchernev** [comment]
Hi @goldsziggy, many thanks for the fix suggestion!

Could you please extend the test here? https://github.com/Surnet/swagger-jsdoc/tree/master/examples/yaml-anchors-aliases to cover for this case of multiple items?

**Comment by kalinchernev** [comment]
I made a few setup tweaks in https://github.com/Surnet/swagger-jsdoc/tree/v7/examples/yaml-anchors-aliases (v7 of the same thing) so to improve focus on working in a smaller project if that would help with writing the tests

**Comment by goldsziggy** [comment]
@kalinchernev I updated the tests for my branch to reflect the bug.  Let me know if that is what you are looking for

**Comment by kalinchernev** [comment]
Many thanks for this fix! @goldsziggy

**Pull request merged**
