### PR TITLE
Update outdated dev dependencies

### PR DESCRIPTION
**Pull request by posquit0**
I upgraded some development dependencies. All test passed with `yarn test` and `yarn test:lint`.

### CODE REVIEW

**Comment by kalinchernev** [comment]
Hi @posquit0 and thanks for the updates! Please remove the tilde (`^`) from the versions, they are intentionally left out because I am not the guy to debug issues with loose dependencies. Takes extremely much time to find issues and tell people consistently to delete `node_modules` folder when issues are simply because of mixtures of versions because of the loose "^".

**Comment by posquit0** [comment]
I did! Thanks for your feedback. :)

**Comment by kalinchernev** [comment]
@posquit0 thanks for the updates! Could you please run `yarn` on clean state (no `node_modules`).
There seemed to be a difference between your current code with versions and the lock file. Like this:

[yarn.lock.zip](https://github.com/Surnet/swagger-jsdoc/files/3365537/yarn.lock.zip) (please don't apply as patch :) it's just for demoing the difference)

Would you mind also removing the `"precommit": "lint-staged"` line from the `package.json` file? It's not related to your changes, but seeing the upgrade of husky I noticed that hasn't been removed in the update of pre v1 to current one :)

**Comment by posquit0** [comment]
I updated my commit with your feedback! :)

**Comment by kalinchernev** [comment]
@posquit0 thanks! :)

**Pull request merged**
