### PR TITLE
Release 1.10.2

### PR DESCRIPTION
**Pull request by kalinchernev**

### CODE REVIEW

**Comment by chdanielmueller** [comment]
First: It's up to you ;)

I would suggest to remove it in swagger-jsdoc and create a new package swagger-jsdoc-cli which depends on swagger-jsdoc.
This way the two projects are able to evolve without interfering with each other.
(+ you will be able to see how many people are working with the CLI -> npm stats)
If you would like I could create another repo.

**Comment by kalinchernev** [comment]
@chdanielmueller not only up to me, that's why I'm asking :)
My first reply would be - yeah - let's take it out and simplify the project, etc.

However, I'm hesitating on the thought, as if there is any of the 62 dependent packages using the CLI, they will fail. This means we go directly to 2.0. No problem from my side to do so.

At the same time, there's https://www.npmjs.com/package/swagger-jsdoc-generator already. The only benefit of someone to use swagger-jsdoc-cli and not swagger-jsdoc-generator would be the watch task.

Another idea would be to remove chokidar. This way we remain compatible for all dependent packages and hopefully remove the problem with the node-gyp. Then, if watch mode is so missed, someone will open an issue and we'll point him to the chokidar package to solve the problem by himself, if one hasn't done so yet.

**Comment by chdanielmueller** [comment]
Yeah if you are able to remove chokidar without removing the cli completely that sounds like the best option to me.

**Comment by chdanielmueller** [comment]
@kalinchernev Maybe @lmammino is interested to implement the watch mode to lmammino/swagger-jsdoc-generator for those missing the feature.

**Pull request merged**
