### PR TITLE
Added filepath to errors report

### PR DESCRIPTION
**Pull request by shady2k**
Added filepath to errors report for better debugging

### CODE REVIEW

**Review by daniloab — COMMENTED** [review]
hi @shady2k, thanks for your work. Can you add tests to your implementation?

**Comment by shady2k** [comment]
> hi @shady2k, thanks for your work. Can you add tests to your implementation?

Added some tests, pls check.

**Comment by daniloab** [comment]
@shady2k js there some failed process, can you check, please?

**Comment by shady2k** [comment]
I've updated my branch.

**Comment by daniloab** [comment]
looks like is missing some snapshot https://github.com/Surnet/swagger-jsdoc/runs/4740310414?check_suite_focus=true#step:4:78 @shady2k

**Comment by shady2k** [comment]
Oh, yes, now it fixed.

**Pull request merged**
