### PR TITLE
Docusaurus Documentation

### PR DESCRIPTION
**Pull request by rockingrohit9639**
I have integrated a docusarus to move the documentation there. 

Initially, I have put the documentation for version 5.x, if everything seems fine then I can process to create documentation for other versions. 

Here is the URL of the live docusaurus documentation [Live Demo](https://silver-dusk-b46ec1.netlify.app/)

Issue #318 

@daniloab

### CODE REVIEW

**Review by daniloab — APPROVED** [review]

**Comment by daniloab** [comment]
@rockingrohit9639 can you fix the problems?

**Comment by rockingrohit9639** [comment]
@daniloab can you please tell me how can I solve these test errors? I have not made any changes in any files other than docusaurus, but it is still throwing errors.

**Comment by daniloab** [comment]
can we have prints of how is going the docs?

**Comment by rockingrohit9639** [comment]
> can we have prints of how is going the docs?

You can see the live preview of docs here [Live Preview](https://silver-dusk-b46ec1.netlify.app/)
It is only for version 5.x, I can add docs for more versions if everything is good with this initial setup.

Here is a demo of the docs
swagger-jsdoc

**Comment by daniloab** [comment]
> > can we have prints of how is going the docs?
> 
> You can see the live preview of docs here [Live Preview](https://silver-dusk-b46ec1.netlify.app/) It is only for version 5.x, I can add docs for more versions if everything is good with this initial setup.
> 
> Here is a demo of the docs swagger-jsdoc [ swagger-jsdoc ](https://user-images.githubusercontent.com/40729749/182613967-620bca96-abc9-4984-bc5b-839f4a6517a9.gif) [ ](https://user-images.githubusercontent.com/40729749/182613967-620bca96-abc9-4984-bc5b-839f4a6517a9.gif)

Looking awesome! Lets move forward

**Comment by rockingrohit9639** [comment]
> > > can we have prints of how is going the docs?
> > 
> > 
> > You can see the live preview of docs here [Live Preview](https://silver-dusk-b46ec1.netlify.app/) It is only for version 5.x, I can add docs for more versions if everything is good with this initial setup.
> > Here is a demo of the docs swagger-jsdoc
> >       
> >         [
> >           
> >             swagger-jsdoc
> >           
> >         ](https://user-images.githubusercontent.com/40729749/182613967-620bca96-abc9-4984-bc5b-839f4a6517a9.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/40729749/182613967-620bca96-abc9-4984-bc5b-839f4a6517a9.gif)
> >         
> >        [ swagger-jsdoc ](https://user-images.githubusercontent.com/40729749/182613967-620bca96-abc9-4984-bc5b-839f4a6517a9.gif)
> >       
> >         [
> >           
> >             swagger-jsdoc
> >           
> >         ](https://user-images.githubusercontent.com/40729749/182613967-620bca96-abc9-4984-bc5b-839f4a6517a9.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/40729749/182613967-620bca96-abc9-4984-bc5b-839f4a6517a9.gif)
> >         
> >        [ ](https://user-images.githubusercontent.com/40729749/182613967-620bca96-abc9-4984-bc5b-839f4a6517a9.gif)
> 
> Looking awesome! Lets move forward

Ok, I will be adding docs for other versions now.

**Comment by daniloab** [comment]
sure, do you prefer send in another pr or still in this one?

**Comment by rockingrohit9639** [comment]
> sure, do you prefer send in another pr or still in this one?

I can do as you want.

**Comment by daniloab** [comment]
lets move forward in another pull requests

**Comment by rockingrohit9639** [comment]
> lets move forward in another pull requests

Okay, great.

**Pull request merged**
