### PR TITLE
Add verbose error logging

### PR DESCRIPTION
**Pull request by jonathanvanschenck**
Addressing Issue #282:
Adds another option to the opts object 'verbose' which will increase the amount of logging for yaml parsing errors:

```js
const swagger_opts = {
    definition : {
        openapi : "3.0.3",
        info : {
            title : "Example"
        },
    },
    apis : [ "./lib/*.js" ],
    failOnErrors : true,
    verbose : true, // I include the file of origin for a yaml parsing error
    // verbose : "vv", // I include the file of origin and the full annotation snippet for a yaml parsing error
};
```

### CODE REVIEW

**Comment by daniloab** [comment]
Hi @jonathanvanschenck first of all thanks for the pr.

Is there an example of how can I test you pr before and after to be inside your branch?

**Comment by jonathanvanschenck** [comment]
Sure, I tried adding a test, but I was having some issues getting it to work in my environment -- I'll give it another go

**Comment by jonathanvanschenck** [comment]
Think I've got some unit tests working now

**Comment by daniloab** [comment]
@jonathanvanschenck can you give a look into the conflicts, please?

**Comment by jonathanvanschenck** [comment]
Rebase to master -- should be good now.

The test suite was throwing a strange error for `examples/yaml-anchors-aliases` but it wasn't causing the test to fail, and I wasn't sure if that was a preexisting problem or not.

**Comment by Yokai1000** [comment]
A merge will be appreciated !!! :) @daniloab

**Pull request merged**
