### PR TITLE
[WIP] options.api allows glob strings

### PR DESCRIPTION
**Pull request by jonboiser**
Re: #19

This is my first pass at the glob feature. Since the `glob` library handles non-glob strings perfectly fine, I simply map-reduce the whole `apis` array through glob, and then pass the resulting array into the for-loop.

Tests still pass, but I'm not sure if a spec was written for this part of the code.

### CODE REVIEW

**Comment by jonboiser** [comment]
I did a test replacing `./example/routes.js` with `./example/*.js` in `example/app.js`. I could extend the example app to illustrate the original use case I put in the original issue.

**Comment by jonboiser** [comment]
I extended the example app to cover this new glob use case.

**Comment by chdanielmueller** [comment]
Hi @jonboiser,
I did take a look at your implementation and it seems fine to me.

But I would like some little changes:
Please remove the definition Login2 from the routes2.js (and also from the swagger-spec.json):
```javascript
  /**
   * @swagger
   * definition:
   *   Login2:
   *     required:
   *       - username
   *       - password
   *     properties:
   *       username:
   *         type: string
   *       password:
   *         type: string
   */
```
And please update the version from 1.2.1 to 1.3.0 in the package.json.

After you have done that I will merge and publish your changes.
Thank you,
Daniel

closes #19

**Comment by jonboiser** [comment]
Done!

**Pull request merged**
