### PR TITLE
feat: update commander version

### PR DESCRIPTION
**Pull request by jamesburns-rts**
Update commander version from 2.20.0 to 2.20.1

Hi! I realize this seems like a small change, but there is a vulnerability in commander 2.20.0 that is causing our build to "fail" :grin:

### CODE REVIEW

**Comment by kalinchernev** [comment]
@jamesburns-rts why not using 4.0.1?

**Comment by jamesburns-rts** [comment]
Since I'm not very familiar with either codebase I was afraid of the "breaking" changes listed in commander change logs, but it looks like your tests pass with either version. Both also work for my use of swagger-jsdoc.

Want me to up it to 4.0.1?

**Comment by kalinchernev** [comment]
@jamesburns-rts yes please, let's go for major upgrade if possible.
The CLI part of the project is separate from the core library and has some coverage. Given the tests are passing and you make 1-3 manual checks, if all goes without problems, then all will be ok :)

**Comment by jamesburns-rts** [comment]
Ok @kalinchernev  sounds good :+1: I have updated it to the latest version.

**Comment by kalinchernev** [comment]
@jamesburns-rts could you please remove the npm lock file, there's already an existing `yarn.lock` in the project.
Thanks!

**Comment by jamesburns-rts** [comment]
Shoot! Embarrassing :man_facepalming: I also seemed to have broken security/snyk

**Comment by kalinchernev** [comment]
@jamesburns-rts thanks for the updates!
It wasn't the change from your side breaking the snyk checks, it was their service. I made a double-check locally, no issues.
Changes are in 3.5.0! Thanks!

**Pull request merged**
